export * from './collections.service';
import { CollectionsService } from './collections.service';
export * from './companies.service';
import { CompaniesService } from './companies.service';
export * from './configuration.service';
import { ConfigurationService } from './configuration.service';
export * from './genre.service';
import { GenreService } from './genre.service';
export * from './keywords.service';
import { KeywordsService } from './keywords.service';
export * from './movieLists.service';
import { MovieListsService } from './movieLists.service';
export * from './movies.service';
import { MoviesService } from './movies.service';
export * from './networks.service';
import { NetworksService } from './networks.service';
export * from './search.service';
import { SearchService } from './search.service';
export * from './tVSeries.service';
import { TVSeriesService } from './tVSeries.service';
export const APIS = [CollectionsService, CompaniesService, ConfigurationService, GenreService, KeywordsService, MovieListsService, MoviesService, NetworksService, SearchService, TVSeriesService];
