export * from './account.service';
import { AccountRestControllerService } from './account.service';
export * from './authentication.service';
import { AuthenticationRestControllerService } from './authentication.service';
export * from './certification.service';
import { CertificationRestControllerService } from './certification.service';
export * from './changes.service';
import { ChangesRestControllerService } from './changes.service';
export * from './collection.service';
import { CollectionRestControllerService } from './collection.service';
export * from './company.service';
import { CompanyRestControllerService } from './company.service';
export * from './configuration.service';
import { ConfigurationRestControllerService } from './configuration.service';
export * from './credit.service';
import { CreditRestControllerService } from './credit.service';
export * from './discover.service';
import { DiscoverRestControllerService } from './discover.service';
export * from './find.service';
import { FindRestControllerService } from './find.service';
export * from './genre.service';
import { GenreRestControllerService } from './genre.service';
export * from './guestSession.service';
import { GuestSessionRestControllerService } from './guestSession.service';
export * from './keyword.service';
import { KeywordRestControllerService } from './keyword.service';
export * from './list.service';
import { ListRestControllerService } from './list.service';
export * from './movie.service';
import { MovieRestControllerService } from './movie.service';
export * from './movieList.service';
import { MovieListRestControllerService } from './movieList.service';
export * from './network.service';
import { NetworkRestControllerService } from './network.service';
export * from './person.service';
import { PersonRestControllerService } from './person.service';
export * from './personList.service';
import { PersonListRestControllerService } from './personList.service';
export * from './review.service';
import { ReviewRestControllerService } from './review.service';
export * from './search.service';
import { SearchRestControllerService } from './search.service';
export * from './trending.service';
import { TrendingRestControllerService } from './trending.service';
export * from './tvEpisode.service';
import { TvEpisodeRestControllerService } from './tvEpisode.service';
export * from './tvEpisodeGroup.service';
import { TvEpisodeGroupRestControllerService } from './tvEpisodeGroup.service';
export * from './tvSeason.service';
import { TvSeasonRestControllerService } from './tvSeason.service';
export * from './tvSeries.service';
import { TvSeriesRestControllerService } from './tvSeries.service';
export * from './tvSeriesList.service';
import { TvSeriesListRestControllerService } from './tvSeriesList.service';
export * from './watchProvider.service';
import { WatchProviderRestControllerService } from './watchProvider.service';
export const APIS = [AccountRestControllerService, AuthenticationRestControllerService, CertificationRestControllerService, ChangesRestControllerService, CollectionRestControllerService, CompanyRestControllerService, ConfigurationRestControllerService, CreditRestControllerService, DiscoverRestControllerService, FindRestControllerService, GenreRestControllerService, GuestSessionRestControllerService, KeywordRestControllerService, ListRestControllerService, MovieRestControllerService, MovieListRestControllerService, NetworkRestControllerService, PersonRestControllerService, PersonListRestControllerService, ReviewRestControllerService, SearchRestControllerService, TrendingRestControllerService, TvEpisodeRestControllerService, TvEpisodeGroupRestControllerService, TvSeasonRestControllerService, TvSeriesRestControllerService, TvSeriesListRestControllerService, WatchProviderRestControllerService];
