/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AccountAddFavoriteRequest } from '../model/models';
import { DeleteSessionResponse } from '../model/models';
import { GuestSessionResponse } from '../model/models';
import { SessionResponse } from '../model/models';
import { StatusResponse } from '../model/models';
import { TokenResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthenticationRestControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create Guest Session
     * 
     * @endpoint get /authentication/guest_session/new
     */
    authenticationCreateGuestSession(extraHttpRequestParams?: any): Observable<GuestSessionResponse>;

    /**
     * Create Request Token
     * 
     * @endpoint get /authentication/token/new
     */
    authenticationCreateRequestToken(extraHttpRequestParams?: any): Observable<TokenResponse>;

    /**
     * Create Session
     * 
     * @endpoint post /authentication/session/new
     * @param accountAddFavoriteRequest 
     */
    authenticationCreateSession(accountAddFavoriteRequest?: AccountAddFavoriteRequest, extraHttpRequestParams?: any): Observable<SessionResponse>;

    /**
     * Create Session (with login)
     * This method allows an application to validate a request token by entering a username and password.
     * @endpoint post /authentication/token/validate_with_login
     * @param accountAddFavoriteRequest 
     */
    authenticationCreateSessionFromLogin(accountAddFavoriteRequest?: AccountAddFavoriteRequest, extraHttpRequestParams?: any): Observable<TokenResponse>;

    /**
     * Create Session (from v4 token)
     * 
     * @endpoint post /authentication/session/convert/4
     * @param accountAddFavoriteRequest 
     */
    authenticationCreateSessionFromV4Token(accountAddFavoriteRequest?: AccountAddFavoriteRequest, extraHttpRequestParams?: any): Observable<SessionResponse>;

    /**
     * Delete Session
     * 
     * @endpoint delete /authentication/session
     * @param accountAddFavoriteRequest 
     */
    authenticationDeleteSession(accountAddFavoriteRequest?: AccountAddFavoriteRequest, extraHttpRequestParams?: any): Observable<DeleteSessionResponse>;

    /**
     * Validate Key
     * Test your API Key to see if it\&#39;s valid.
     * @endpoint get /authentication
     */
    authenticationValidateKey(extraHttpRequestParams?: any): Observable<StatusResponse>;

}
