/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AlternativeNameList } from '../model/models';
import { CompanyDetails } from '../model/models';
import { CompanyImages } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface CompanyRestControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Alternative Names
     * Get the company details by ID.
     * @endpoint get /company/{company_id}/alternative_names
     * @param companyId 
     */
    companyAlternativeNames(companyId: number, extraHttpRequestParams?: any): Observable<AlternativeNameList>;

    /**
     * Details
     * Get the company details by ID.
     * @endpoint get /company/{company_id}
     * @param companyId 
     */
    companyDetails(companyId: number, extraHttpRequestParams?: any): Observable<CompanyDetails>;

    /**
     * Images
     * Get the company logos by id.
     * @endpoint get /company/{company_id}/images
     * @param companyId 
     */
    companyImages(companyId: number, extraHttpRequestParams?: any): Observable<CompanyImages>;

}
