/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpContext 
        }       from '@angular/common/http';
import { Observable }                                        from 'rxjs';
import { OpenApiHttpParams, QueryParamStyle } from '../query.params';

// @ts-ignore
import { MoviePage } from '../model/moviePage';
// @ts-ignore
import { TvSeriesPage } from '../model/tvSeriesPage';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
  providedIn: 'root'
})
export class DiscoverRestControllerService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Movie
     * Find movies using over 30 filters and sort options.
     * @endpoint get /discover/movie
     * @param certification use in conjunction with &#x60;region&#x60;
     * @param certificationGte use in conjunction with &#x60;region&#x60;
     * @param certificationLte use in conjunction with &#x60;region&#x60;
     * @param certificationCountry use in conjunction with the &#x60;certification&#x60;, &#x60;certification.gte&#x60; and &#x60;certification.lte&#x60; filters
     * @param includeAdult 
     * @param includeVideo 
     * @param language 
     * @param page 
     * @param primaryReleaseYear 
     * @param primaryReleaseDateGte 
     * @param primaryReleaseDateLte 
     * @param region 
     * @param releaseDateGte 
     * @param releaseDateLte 
     * @param sortBy 
     * @param voteAverageGte 
     * @param voteAverageLte 
     * @param voteCountGte 
     * @param voteCountLte 
     * @param watchRegion use in conjunction with &#x60;with_watch_monetization_types &#x60; or &#x60;with_watch_providers &#x60;
     * @param withCast can be a comma (&#x60;AND&#x60;) or pipe (&#x60;OR&#x60;) separated query
     * @param withCompanies can be a comma (&#x60;AND&#x60;) or pipe (&#x60;OR&#x60;) separated query
     * @param withCrew can be a comma (&#x60;AND&#x60;) or pipe (&#x60;OR&#x60;) separated query
     * @param withGenres can be a comma (&#x60;AND&#x60;) or pipe (&#x60;OR&#x60;) separated query
     * @param withKeywords can be a comma (&#x60;AND&#x60;) or pipe (&#x60;OR&#x60;) separated query
     * @param withOriginCountry 
     * @param withOriginalLanguage 
     * @param withPeople can be a comma (&#x60;AND&#x60;) or pipe (&#x60;OR&#x60;) separated query
     * @param withReleaseType possible values are: [1, 2, 3, 4, 5, 6] can be a comma (&#x60;AND&#x60;) or pipe (&#x60;OR&#x60;) separated query, can be used in conjunction with &#x60;region&#x60;
     * @param withRuntimeGte 
     * @param withRuntimeLte 
     * @param withWatchMonetizationTypes possible values are: [flatrate, free, ads, rent, buy] use in conjunction with &#x60;watch_region&#x60;, can be a comma (&#x60;AND&#x60;) or pipe (&#x60;OR&#x60;) separated query
     * @param withWatchProviders use in conjunction with &#x60;watch_region&#x60;, can be a comma (&#x60;AND&#x60;) or pipe (&#x60;OR&#x60;) separated query
     * @param withoutCompanies 
     * @param withoutGenres 
     * @param withoutKeywords 
     * @param withoutWatchProviders 
     * @param year 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public discoverMovie(certification?: string, certificationGte?: string, certificationLte?: string, certificationCountry?: string, includeAdult?: boolean, includeVideo?: boolean, language?: string, page?: number, primaryReleaseYear?: number, primaryReleaseDateGte?: string, primaryReleaseDateLte?: string, region?: string, releaseDateGte?: string, releaseDateLte?: string, sortBy?: 'original_title.asc' | 'original_title.desc' | 'popularity.asc' | 'popularity.desc' | 'revenue.asc' | 'revenue.desc' | 'primary_release_date.asc' | 'title.asc' | 'title.desc' | 'primary_release_date.desc' | 'vote_average.asc' | 'vote_average.desc' | 'vote_count.asc' | 'vote_count.desc', voteAverageGte?: number, voteAverageLte?: number, voteCountGte?: number, voteCountLte?: number, watchRegion?: string, withCast?: string, withCompanies?: string, withCrew?: string, withGenres?: string, withKeywords?: string, withOriginCountry?: string, withOriginalLanguage?: string, withPeople?: string, withReleaseType?: number, withRuntimeGte?: number, withRuntimeLte?: number, withWatchMonetizationTypes?: string, withWatchProviders?: string, withoutCompanies?: string, withoutGenres?: string, withoutKeywords?: string, withoutWatchProviders?: string, year?: number, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<MoviePage>;
    public discoverMovie(certification?: string, certificationGte?: string, certificationLte?: string, certificationCountry?: string, includeAdult?: boolean, includeVideo?: boolean, language?: string, page?: number, primaryReleaseYear?: number, primaryReleaseDateGte?: string, primaryReleaseDateLte?: string, region?: string, releaseDateGte?: string, releaseDateLte?: string, sortBy?: 'original_title.asc' | 'original_title.desc' | 'popularity.asc' | 'popularity.desc' | 'revenue.asc' | 'revenue.desc' | 'primary_release_date.asc' | 'title.asc' | 'title.desc' | 'primary_release_date.desc' | 'vote_average.asc' | 'vote_average.desc' | 'vote_count.asc' | 'vote_count.desc', voteAverageGte?: number, voteAverageLte?: number, voteCountGte?: number, voteCountLte?: number, watchRegion?: string, withCast?: string, withCompanies?: string, withCrew?: string, withGenres?: string, withKeywords?: string, withOriginCountry?: string, withOriginalLanguage?: string, withPeople?: string, withReleaseType?: number, withRuntimeGte?: number, withRuntimeLte?: number, withWatchMonetizationTypes?: string, withWatchProviders?: string, withoutCompanies?: string, withoutGenres?: string, withoutKeywords?: string, withoutWatchProviders?: string, year?: number, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<MoviePage>>;
    public discoverMovie(certification?: string, certificationGte?: string, certificationLte?: string, certificationCountry?: string, includeAdult?: boolean, includeVideo?: boolean, language?: string, page?: number, primaryReleaseYear?: number, primaryReleaseDateGte?: string, primaryReleaseDateLte?: string, region?: string, releaseDateGte?: string, releaseDateLte?: string, sortBy?: 'original_title.asc' | 'original_title.desc' | 'popularity.asc' | 'popularity.desc' | 'revenue.asc' | 'revenue.desc' | 'primary_release_date.asc' | 'title.asc' | 'title.desc' | 'primary_release_date.desc' | 'vote_average.asc' | 'vote_average.desc' | 'vote_count.asc' | 'vote_count.desc', voteAverageGte?: number, voteAverageLte?: number, voteCountGte?: number, voteCountLte?: number, watchRegion?: string, withCast?: string, withCompanies?: string, withCrew?: string, withGenres?: string, withKeywords?: string, withOriginCountry?: string, withOriginalLanguage?: string, withPeople?: string, withReleaseType?: number, withRuntimeGte?: number, withRuntimeLte?: number, withWatchMonetizationTypes?: string, withWatchProviders?: string, withoutCompanies?: string, withoutGenres?: string, withoutKeywords?: string, withoutWatchProviders?: string, year?: number, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<MoviePage>>;
    public discoverMovie(certification?: string, certificationGte?: string, certificationLte?: string, certificationCountry?: string, includeAdult?: boolean, includeVideo?: boolean, language?: string, page?: number, primaryReleaseYear?: number, primaryReleaseDateGte?: string, primaryReleaseDateLte?: string, region?: string, releaseDateGte?: string, releaseDateLte?: string, sortBy?: 'original_title.asc' | 'original_title.desc' | 'popularity.asc' | 'popularity.desc' | 'revenue.asc' | 'revenue.desc' | 'primary_release_date.asc' | 'title.asc' | 'title.desc' | 'primary_release_date.desc' | 'vote_average.asc' | 'vote_average.desc' | 'vote_count.asc' | 'vote_count.desc', voteAverageGte?: number, voteAverageLte?: number, voteCountGte?: number, voteCountLte?: number, watchRegion?: string, withCast?: string, withCompanies?: string, withCrew?: string, withGenres?: string, withKeywords?: string, withOriginCountry?: string, withOriginalLanguage?: string, withPeople?: string, withReleaseType?: number, withRuntimeGte?: number, withRuntimeLte?: number, withWatchMonetizationTypes?: string, withWatchProviders?: string, withoutCompanies?: string, withoutGenres?: string, withoutKeywords?: string, withoutWatchProviders?: string, year?: number, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'certification',
            <any>certification,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'certification.gte',
            <any>certificationGte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'certification.lte',
            <any>certificationLte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'certification_country',
            <any>certificationCountry,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'include_adult',
            <any>includeAdult,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'include_video',
            <any>includeVideo,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'language',
            <any>language,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'page',
            <any>page,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'primary_release_year',
            <any>primaryReleaseYear,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'primary_release_date.gte',
            <any>primaryReleaseDateGte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'primary_release_date.lte',
            <any>primaryReleaseDateLte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'region',
            <any>region,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'release_date.gte',
            <any>releaseDateGte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'release_date.lte',
            <any>releaseDateLte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'sort_by',
            <any>sortBy,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'vote_average.gte',
            <any>voteAverageGte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'vote_average.lte',
            <any>voteAverageLte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'vote_count.gte',
            <any>voteCountGte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'vote_count.lte',
            <any>voteCountLte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'watch_region',
            <any>watchRegion,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_cast',
            <any>withCast,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_companies',
            <any>withCompanies,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_crew',
            <any>withCrew,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_genres',
            <any>withGenres,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_keywords',
            <any>withKeywords,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_origin_country',
            <any>withOriginCountry,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_original_language',
            <any>withOriginalLanguage,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_people',
            <any>withPeople,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_release_type',
            <any>withReleaseType,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_runtime.gte',
            <any>withRuntimeGte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_runtime.lte',
            <any>withRuntimeLte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_watch_monetization_types',
            <any>withWatchMonetizationTypes,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_watch_providers',
            <any>withWatchProviders,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'without_companies',
            <any>withoutCompanies,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'without_genres',
            <any>withoutGenres,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'without_keywords',
            <any>withoutKeywords,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'without_watch_providers',
            <any>withoutWatchProviders,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'year',
            <any>year,
            QueryParamStyle.Form,
            true,
        );


        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/discover/movie`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<MoviePage>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters.toHttpParams(),
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * TV
     * Find TV shows using over 30 filters and sort options.
     * @endpoint get /discover/tv
     * @param airDateGte 
     * @param airDateLte 
     * @param firstAirDateYear 
     * @param firstAirDateGte 
     * @param firstAirDateLte 
     * @param includeAdult 
     * @param includeNullFirstAirDates 
     * @param language 
     * @param page 
     * @param screenedTheatrically 
     * @param sortBy 
     * @param timezone 
     * @param voteAverageGte 
     * @param voteAverageLte 
     * @param voteCountGte 
     * @param voteCountLte 
     * @param watchRegion use in conjunction with &#x60;with_watch_monetization_types &#x60; or &#x60;with_watch_providers &#x60;
     * @param withCompanies can be a comma (&#x60;AND&#x60;) or pipe (&#x60;OR&#x60;) separated query
     * @param withGenres can be a comma (&#x60;AND&#x60;) or pipe (&#x60;OR&#x60;) separated query
     * @param withKeywords can be a comma (&#x60;AND&#x60;) or pipe (&#x60;OR&#x60;) separated query
     * @param withNetworks 
     * @param withOriginCountry 
     * @param withOriginalLanguage 
     * @param withRuntimeGte 
     * @param withRuntimeLte 
     * @param withStatus possible values are: [0, 1, 2, 3, 4, 5], can be a comma (&#x60;AND&#x60;) or pipe (&#x60;OR&#x60;) separated query
     * @param withWatchMonetizationTypes possible values are: [flatrate, free, ads, rent, buy] use in conjunction with &#x60;watch_region&#x60;, can be a comma (&#x60;AND&#x60;) or pipe (&#x60;OR&#x60;) separated query
     * @param withWatchProviders use in conjunction with &#x60;watch_region&#x60;, can be a comma (&#x60;AND&#x60;) or pipe (&#x60;OR&#x60;) separated query
     * @param withoutCompanies 
     * @param withoutGenres 
     * @param withoutKeywords 
     * @param withoutWatchProviders 
     * @param withType possible values are: [0, 1, 2, 3, 4, 5, 6], can be a comma (&#x60;AND&#x60;) or pipe (&#x60;OR&#x60;) separated query
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public discoverTv(airDateGte?: string, airDateLte?: string, firstAirDateYear?: number, firstAirDateGte?: string, firstAirDateLte?: string, includeAdult?: boolean, includeNullFirstAirDates?: boolean, language?: string, page?: number, screenedTheatrically?: boolean, sortBy?: 'first_air_date.asc' | 'first_air_date.desc' | 'name.asc' | 'name.desc' | 'original_name.asc' | 'original_name.desc' | 'popularity.asc' | 'popularity.desc' | 'vote_average.asc' | 'vote_average.desc' | 'vote_count.asc' | 'vote_count.desc', timezone?: string, voteAverageGte?: number, voteAverageLte?: number, voteCountGte?: number, voteCountLte?: number, watchRegion?: string, withCompanies?: string, withGenres?: string, withKeywords?: string, withNetworks?: number, withOriginCountry?: string, withOriginalLanguage?: string, withRuntimeGte?: number, withRuntimeLte?: number, withStatus?: string, withWatchMonetizationTypes?: string, withWatchProviders?: string, withoutCompanies?: string, withoutGenres?: string, withoutKeywords?: string, withoutWatchProviders?: string, withType?: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<TvSeriesPage>;
    public discoverTv(airDateGte?: string, airDateLte?: string, firstAirDateYear?: number, firstAirDateGte?: string, firstAirDateLte?: string, includeAdult?: boolean, includeNullFirstAirDates?: boolean, language?: string, page?: number, screenedTheatrically?: boolean, sortBy?: 'first_air_date.asc' | 'first_air_date.desc' | 'name.asc' | 'name.desc' | 'original_name.asc' | 'original_name.desc' | 'popularity.asc' | 'popularity.desc' | 'vote_average.asc' | 'vote_average.desc' | 'vote_count.asc' | 'vote_count.desc', timezone?: string, voteAverageGte?: number, voteAverageLte?: number, voteCountGte?: number, voteCountLte?: number, watchRegion?: string, withCompanies?: string, withGenres?: string, withKeywords?: string, withNetworks?: number, withOriginCountry?: string, withOriginalLanguage?: string, withRuntimeGte?: number, withRuntimeLte?: number, withStatus?: string, withWatchMonetizationTypes?: string, withWatchProviders?: string, withoutCompanies?: string, withoutGenres?: string, withoutKeywords?: string, withoutWatchProviders?: string, withType?: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<TvSeriesPage>>;
    public discoverTv(airDateGte?: string, airDateLte?: string, firstAirDateYear?: number, firstAirDateGte?: string, firstAirDateLte?: string, includeAdult?: boolean, includeNullFirstAirDates?: boolean, language?: string, page?: number, screenedTheatrically?: boolean, sortBy?: 'first_air_date.asc' | 'first_air_date.desc' | 'name.asc' | 'name.desc' | 'original_name.asc' | 'original_name.desc' | 'popularity.asc' | 'popularity.desc' | 'vote_average.asc' | 'vote_average.desc' | 'vote_count.asc' | 'vote_count.desc', timezone?: string, voteAverageGte?: number, voteAverageLte?: number, voteCountGte?: number, voteCountLte?: number, watchRegion?: string, withCompanies?: string, withGenres?: string, withKeywords?: string, withNetworks?: number, withOriginCountry?: string, withOriginalLanguage?: string, withRuntimeGte?: number, withRuntimeLte?: number, withStatus?: string, withWatchMonetizationTypes?: string, withWatchProviders?: string, withoutCompanies?: string, withoutGenres?: string, withoutKeywords?: string, withoutWatchProviders?: string, withType?: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<TvSeriesPage>>;
    public discoverTv(airDateGte?: string, airDateLte?: string, firstAirDateYear?: number, firstAirDateGte?: string, firstAirDateLte?: string, includeAdult?: boolean, includeNullFirstAirDates?: boolean, language?: string, page?: number, screenedTheatrically?: boolean, sortBy?: 'first_air_date.asc' | 'first_air_date.desc' | 'name.asc' | 'name.desc' | 'original_name.asc' | 'original_name.desc' | 'popularity.asc' | 'popularity.desc' | 'vote_average.asc' | 'vote_average.desc' | 'vote_count.asc' | 'vote_count.desc', timezone?: string, voteAverageGte?: number, voteAverageLte?: number, voteCountGte?: number, voteCountLte?: number, watchRegion?: string, withCompanies?: string, withGenres?: string, withKeywords?: string, withNetworks?: number, withOriginCountry?: string, withOriginalLanguage?: string, withRuntimeGte?: number, withRuntimeLte?: number, withStatus?: string, withWatchMonetizationTypes?: string, withWatchProviders?: string, withoutCompanies?: string, withoutGenres?: string, withoutKeywords?: string, withoutWatchProviders?: string, withType?: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'air_date.gte',
            <any>airDateGte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'air_date.lte',
            <any>airDateLte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'first_air_date_year',
            <any>firstAirDateYear,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'first_air_date.gte',
            <any>firstAirDateGte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'first_air_date.lte',
            <any>firstAirDateLte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'include_adult',
            <any>includeAdult,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'include_null_first_air_dates',
            <any>includeNullFirstAirDates,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'language',
            <any>language,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'page',
            <any>page,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'screened_theatrically',
            <any>screenedTheatrically,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'sort_by',
            <any>sortBy,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'timezone',
            <any>timezone,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'vote_average.gte',
            <any>voteAverageGte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'vote_average.lte',
            <any>voteAverageLte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'vote_count.gte',
            <any>voteCountGte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'vote_count.lte',
            <any>voteCountLte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'watch_region',
            <any>watchRegion,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_companies',
            <any>withCompanies,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_genres',
            <any>withGenres,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_keywords',
            <any>withKeywords,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_networks',
            <any>withNetworks,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_origin_country',
            <any>withOriginCountry,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_original_language',
            <any>withOriginalLanguage,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_runtime.gte',
            <any>withRuntimeGte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_runtime.lte',
            <any>withRuntimeLte,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_status',
            <any>withStatus,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_watch_monetization_types',
            <any>withWatchMonetizationTypes,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_watch_providers',
            <any>withWatchProviders,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'without_companies',
            <any>withoutCompanies,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'without_genres',
            <any>withoutGenres,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'without_keywords',
            <any>withoutKeywords,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'without_watch_providers',
            <any>withoutWatchProviders,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'with_type',
            <any>withType,
            QueryParamStyle.Form,
            true,
        );


        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/discover/tv`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<TvSeriesPage>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters.toHttpParams(),
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
