/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { FindResult } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface FindRestControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Find By ID
     * Find data by external ID\&#39;s.
     * @endpoint get /find/{external_id}
     * @param externalId 
     * @param externalSource 
     * @param language 
     */
    findById(externalId: string, externalSource: 'imdb_id' | 'facebook_id' | 'instagram_id' | 'tvdb_id' | 'tiktok_id' | 'twitter_id' | 'wikidata_id' | 'youtube_id', language?: string, extraHttpRequestParams?: any): Observable<FindResult>;

}
