/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { GenreList } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface GenreRestControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Movie List
     * Get the list of official genres for movies.
     * @endpoint get /genre/movie/list
     * @param language 
     */
    genreMovieList(language?: string, extraHttpRequestParams?: any): Observable<GenreList>;

    /**
     * TV List
     * Get the list of official genres for TV shows.
     * @endpoint get /genre/tv/list
     * @param language 
     */
    genreTvList(language?: string, extraHttpRequestParams?: any): Observable<GenreList>;

}
