/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { RatedMoviePage } from '../model/models';
import { RatedTvEpisodePage } from '../model/models';
import { RatedTvSeriesPage } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface GuestSessionRestControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Rated Movies
     * Get the rated movies for a guest session.
     * @endpoint get /guest_session/{guest_session_id}/rated/movies
     * @param guestSessionId 
     * @param language 
     * @param page 
     * @param sortBy 
     */
    guestSessionRatedMovies(guestSessionId: string, language?: string, page?: number, sortBy?: 'created_at.asc' | 'created_at.desc', extraHttpRequestParams?: any): Observable<RatedMoviePage>;

    /**
     * Rated TV
     * Get the rated TV shows for a guest session.
     * @endpoint get /guest_session/{guest_session_id}/rated/tv
     * @param guestSessionId 
     * @param language 
     * @param page 
     * @param sortBy 
     */
    guestSessionRatedTv(guestSessionId: string, language?: string, page?: number, sortBy?: 'created_at.asc' | 'created_at.desc', extraHttpRequestParams?: any): Observable<RatedTvSeriesPage>;

    /**
     * Rated TV Episodes
     * Get the rated TV episodes for a guest session.
     * @endpoint get /guest_session/{guest_session_id}/rated/tv/episodes
     * @param guestSessionId 
     * @param language 
     * @param page 
     * @param sortBy 
     */
    guestSessionRatedTvEpisodes(guestSessionId: string, language?: string, page?: number, sortBy?: 'created_at.asc' | 'created_at.desc', extraHttpRequestParams?: any): Observable<RatedTvEpisodePage>;

}
