/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AccountAddFavoriteRequest } from '../model/models';
import { AccountStates } from '../model/models';
import { AlternativeTitleList } from '../model/models';
import { ChangeList } from '../model/models';
import { Credits } from '../model/models';
import { ExternalIds } from '../model/models';
import { ImageList } from '../model/models';
import { KeywordList } from '../model/models';
import { Movie } from '../model/models';
import { MovieListPage } from '../model/models';
import { MoviePage } from '../model/models';
import { ReleaseDateList } from '../model/models';
import { ReviewPage } from '../model/models';
import { StatusResponse } from '../model/models';
import { TranslationList } from '../model/models';
import { VideoList } from '../model/models';
import { WatchProviderList } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface MovieRestControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Account States
     * Get the rating, watchlist and favourite status of an account.
     * @endpoint get /movie/{movie_id}/account_states
     * @param movieId 
     * @param sessionId 
     * @param guestSessionId 
     */
    movieAccountStates(movieId: number, sessionId?: string, guestSessionId?: string, extraHttpRequestParams?: any): Observable<AccountStates>;

    /**
     * Add Rating
     * Rate a movie and save it to your rated list.
     * @endpoint post /movie/{movie_id}/rating
     * @param movieId 
     * @param contentType 
     * @param guestSessionId 
     * @param sessionId 
     * @param accountAddFavoriteRequest 
     */
    movieAddRating(movieId: number, contentType: string, guestSessionId?: string, sessionId?: string, accountAddFavoriteRequest?: AccountAddFavoriteRequest, extraHttpRequestParams?: any): Observable<StatusResponse>;

    /**
     * Alternative Titles
     * Get the alternative titles for a movie.
     * @endpoint get /movie/{movie_id}/alternative_titles
     * @param movieId 
     * @param country specify a ISO-3166-1 value to filter the results
     */
    movieAlternativeTitles(movieId: number, country?: string, extraHttpRequestParams?: any): Observable<AlternativeTitleList>;

    /**
     * Changes
     * Get the recent changes for a movie.
     * @endpoint get /movie/{movie_id}/changes
     * @param movieId 
     * @param endDate 
     * @param page 
     * @param startDate 
     */
    movieChanges(movieId: number, endDate?: string, page?: number, startDate?: string, extraHttpRequestParams?: any): Observable<ChangeList>;

    /**
     * Credits
     * 
     * @endpoint get /movie/{movie_id}/credits
     * @param movieId 
     * @param language 
     */
    movieCredits(movieId: number, language?: string, extraHttpRequestParams?: any): Observable<Credits>;

    /**
     * Delete Rating
     * Delete a user rating.
     * @endpoint delete /movie/{movie_id}/rating
     * @param movieId 
     * @param contentType 
     * @param guestSessionId 
     * @param sessionId 
     */
    movieDeleteRating(movieId: number, contentType?: string, guestSessionId?: string, sessionId?: string, extraHttpRequestParams?: any): Observable<StatusResponse>;

    /**
     * Details
     * Get the top level details of a movie by ID.
     * @endpoint get /movie/{movie_id}
     * @param movieId 
     * @param appendToResponse comma separated list of endpoints within this namespace, 20 items max
     * @param language 
     */
    movieDetails(movieId: number, appendToResponse?: string, language?: string, extraHttpRequestParams?: any): Observable<Movie>;

    /**
     * External IDs
     * 
     * @endpoint get /movie/{movie_id}/external_ids
     * @param movieId 
     */
    movieExternalIds(movieId: number, extraHttpRequestParams?: any): Observable<ExternalIds>;

    /**
     * Images
     * Get the images that belong to a movie.
     * @endpoint get /movie/{movie_id}/images
     * @param movieId 
     * @param includeImageLanguage specify a comma separated list of ISO-639-1 values to query, for example: &#x60;en-US,null&#x60;
     * @param language 
     */
    movieImages(movieId: number, includeImageLanguage?: string, language?: string, extraHttpRequestParams?: any): Observable<ImageList>;

    /**
     * Keywords
     * 
     * @endpoint get /movie/{movie_id}/keywords
     * @param movieId 
     */
    movieKeywords(movieId: string, extraHttpRequestParams?: any): Observable<KeywordList>;

    /**
     * Lists
     * Get the lists that a movie has been added to.
     * @endpoint get /movie/{movie_id}/lists
     * @param movieId 
     * @param language 
     * @param page 
     */
    movieLists(movieId: number, language?: string, page?: number, extraHttpRequestParams?: any): Observable<MovieListPage>;

    /**
     * Recommendations
     * 
     * @endpoint get /movie/{movie_id}/recommendations
     * @param movieId 
     * @param language 
     * @param page 
     */
    movieRecommendations(movieId: number, language?: string, page?: number, extraHttpRequestParams?: any): Observable<MoviePage>;

    /**
     * Release Dates
     * Get the release dates and certifications for a movie.
     * @endpoint get /movie/{movie_id}/release_dates
     * @param movieId 
     */
    movieReleaseDates(movieId: number, extraHttpRequestParams?: any): Observable<ReleaseDateList>;

    /**
     * Reviews
     * Get the user reviews for a movie.
     * @endpoint get /movie/{movie_id}/reviews
     * @param movieId 
     * @param language 
     * @param page 
     */
    movieReviews(movieId: number, language?: string, page?: number, extraHttpRequestParams?: any): Observable<ReviewPage>;

    /**
     * Similar
     * Get the similar movies based on genres and keywords.
     * @endpoint get /movie/{movie_id}/similar
     * @param movieId 
     * @param language 
     * @param page 
     */
    movieSimilar(movieId: number, language?: string, page?: number, extraHttpRequestParams?: any): Observable<MoviePage>;

    /**
     * Translations
     * Get the translations for a movie.
     * @endpoint get /movie/{movie_id}/translations
     * @param movieId 
     */
    movieTranslations(movieId: number, extraHttpRequestParams?: any): Observable<TranslationList>;

    /**
     * Videos
     * 
     * @endpoint get /movie/{movie_id}/videos
     * @param movieId 
     * @param language 
     */
    movieVideos(movieId: number, language?: string, extraHttpRequestParams?: any): Observable<VideoList>;

    /**
     * Watch Providers
     * Get the list of streaming providers we have for a movie.
     * @endpoint get /movie/{movie_id}/watch/providers
     * @param movieId 
     */
    movieWatchProviders(movieId: number, extraHttpRequestParams?: any): Observable<WatchProviderList>;

}
