/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Movie } from '../model/models';
import { MoviePage } from '../model/models';
import { MoviePageWithDates } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface MovieListRestControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Latest
     * Get the newest movie ID.
     * @endpoint get /movie/latest
     */
    movieLatestId(extraHttpRequestParams?: any): Observable<Movie>;

    /**
     * Now Playing
     * Get a list of movies that are currently in theatres.
     * @endpoint get /movie/now_playing
     * @param language 
     * @param page 
     * @param region ISO-3166-1 code
     */
    movieNowPlayingList(language?: string, page?: number, region?: string, extraHttpRequestParams?: any): Observable<MoviePageWithDates>;

    /**
     * Popular
     * Get a list of movies ordered by popularity.
     * @endpoint get /movie/popular
     * @param language 
     * @param page 
     * @param region ISO-3166-1 code
     */
    moviePopularList(language?: string, page?: number, region?: string, extraHttpRequestParams?: any): Observable<MoviePage>;

    /**
     * Top Rated
     * Get a list of movies ordered by rating.
     * @endpoint get /movie/top_rated
     * @param language 
     * @param page 
     * @param region ISO-3166-1 code
     */
    movieTopRatedList(language?: string, page?: number, region?: string, extraHttpRequestParams?: any): Observable<MoviePage>;

    /**
     * Upcoming
     * Get a list of movies that are being released soon.
     * @endpoint get /movie/upcoming
     * @param language 
     * @param page 
     * @param region ISO-3166-1 code
     */
    movieUpcomingList(language?: string, page?: number, region?: string, extraHttpRequestParams?: any): Observable<MoviePageWithDates>;

}
