/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AccountAddFavoriteRequest } from '../model/models';
import { AccountStates } from '../model/models';
import { ChangeList } from '../model/models';
import { StatusResponse } from '../model/models';
import { TranslationList } from '../model/models';
import { TvEpisode } from '../model/models';
import { TvEpisodeCredits } from '../model/models';
import { TvEpisodeExternalIds } from '../model/models';
import { TvEpisodeImages } from '../model/models';
import { VideoList } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface TvEpisodeRestControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Account States
     * Get the rating, watchlist and favourite status.
     * @endpoint get /tv/{series_id}/season/{season_number}/episode/{episode_number}/account_states
     * @param seriesId 
     * @param seasonNumber 
     * @param episodeNumber 
     * @param sessionId 
     * @param guestSessionId 
     */
    tvEpisodeAccountStates(seriesId: number, seasonNumber: number, episodeNumber: number, sessionId?: string, guestSessionId?: string, extraHttpRequestParams?: any): Observable<AccountStates>;

    /**
     * Add Rating
     * Rate a TV episode and save it to your rated list.
     * @endpoint post /tv/{series_id}/season/{season_number}/episode/{episode_number}/rating
     * @param seriesId 
     * @param contentType 
     * @param seasonNumber 
     * @param episodeNumber 
     * @param guestSessionId 
     * @param sessionId 
     * @param accountAddFavoriteRequest 
     */
    tvEpisodeAddRating(seriesId: number, contentType: string, seasonNumber: number, episodeNumber: number, guestSessionId?: string, sessionId?: string, accountAddFavoriteRequest?: AccountAddFavoriteRequest, extraHttpRequestParams?: any): Observable<StatusResponse>;

    /**
     * Changes
     * Get the recent changes for a TV episode.
     * @endpoint get /tv/episode/{episode_id}/changes
     * @param episodeId 
     */
    tvEpisodeChangesById(episodeId: number, extraHttpRequestParams?: any): Observable<ChangeList>;

    /**
     * Credits
     * 
     * @endpoint get /tv/{series_id}/season/{season_number}/episode/{episode_number}/credits
     * @param seriesId 
     * @param seasonNumber 
     * @param episodeNumber 
     * @param language 
     */
    tvEpisodeCredits(seriesId: number, seasonNumber: number, episodeNumber: number, language?: string, extraHttpRequestParams?: any): Observable<TvEpisodeCredits>;

    /**
     * Delete Rating
     * Delete your rating on a TV episode.
     * @endpoint delete /tv/{series_id}/season/{season_number}/episode/{episode_number}/rating
     * @param seriesId 
     * @param seasonNumber 
     * @param episodeNumber 
     * @param contentType 
     * @param guestSessionId 
     * @param sessionId 
     */
    tvEpisodeDeleteRating(seriesId: number, seasonNumber: number, episodeNumber: number, contentType?: string, guestSessionId?: string, sessionId?: string, extraHttpRequestParams?: any): Observable<StatusResponse>;

    /**
     * Details
     * Query the details of a TV episode.
     * @endpoint get /tv/{series_id}/season/{season_number}/episode/{episode_number}
     * @param seriesId 
     * @param seasonNumber 
     * @param episodeNumber 
     * @param appendToResponse comma separated list of endpoints within this namespace, 20 items max
     * @param language 
     */
    tvEpisodeDetails(seriesId: number, seasonNumber: number, episodeNumber: number, appendToResponse?: string, language?: string, extraHttpRequestParams?: any): Observable<TvEpisode>;

    /**
     * External IDs
     * Get a list of external IDs that have been added to a TV episode.
     * @endpoint get /tv/{series_id}/season/{season_number}/episode/{episode_number}/external_ids
     * @param seriesId 
     * @param seasonNumber 
     * @param episodeNumber 
     */
    tvEpisodeExternalIds(seriesId: number, seasonNumber: number, episodeNumber: string, extraHttpRequestParams?: any): Observable<TvEpisodeExternalIds>;

    /**
     * Images
     * Get the images that belong to a TV episode.
     * @endpoint get /tv/{series_id}/season/{season_number}/episode/{episode_number}/images
     * @param seriesId 
     * @param seasonNumber 
     * @param episodeNumber 
     * @param includeImageLanguage specify a comma separated list of ISO-639-1 values to query, for example: &#x60;en-US,null&#x60;
     * @param language 
     */
    tvEpisodeImages(seriesId: number, seasonNumber: number, episodeNumber: number, includeImageLanguage?: string, language?: string, extraHttpRequestParams?: any): Observable<TvEpisodeImages>;

    /**
     * Translations
     * Get the translations that have been added to a TV episode.
     * @endpoint get /tv/{series_id}/season/{season_number}/episode/{episode_number}/translations
     * @param seriesId 
     * @param seasonNumber 
     * @param episodeNumber 
     */
    tvEpisodeTranslations(seriesId: number, seasonNumber: number, episodeNumber: number, extraHttpRequestParams?: any): Observable<TranslationList>;

    /**
     * Videos
     * Get the videos that belong to a TV episode.
     * @endpoint get /tv/{series_id}/season/{season_number}/episode/{episode_number}/videos
     * @param seriesId 
     * @param seasonNumber 
     * @param episodeNumber 
     * @param includeVideoLanguage filter the list results by language, supports more than one value by using a comma
     * @param language 
     */
    tvEpisodeVideos(seriesId: number, seasonNumber: number, episodeNumber: number, includeVideoLanguage?: string, language?: string, extraHttpRequestParams?: any): Observable<VideoList>;

}
