/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AccountAddFavoriteRequest } from '../model/models';
import { AccountStates } from '../model/models';
import { AggregateCredits } from '../model/models';
import { ChangeList } from '../model/models';
import { ContentRatingList } from '../model/models';
import { Credits } from '../model/models';
import { EpisodeGroupList } from '../model/models';
import { ImageList } from '../model/models';
import { ReviewPage } from '../model/models';
import { ScreenedTheatricallyList } from '../model/models';
import { StatusResponse } from '../model/models';
import { TranslationList } from '../model/models';
import { TvAlternativeTitleList } from '../model/models';
import { TvExternalIds } from '../model/models';
import { TvKeywordList } from '../model/models';
import { TvSeries } from '../model/models';
import { TvSeriesListPage } from '../model/models';
import { TvSeriesPage } from '../model/models';
import { VideoList } from '../model/models';
import { WatchProviderList } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface TvSeriesRestControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Lists
     * Get the lists that a TV series has been added to.
     * @endpoint get /tv/{series_id}/lists
     * @param seriesId 
     * @param language 
     * @param page 
     */
    listsCopy(seriesId: number, language?: string, page?: number, extraHttpRequestParams?: any): Observable<TvSeriesListPage>;

    /**
     * Account States
     * Get the rating, watchlist and favourite status.
     * @endpoint get /tv/{series_id}/account_states
     * @param seriesId 
     * @param sessionId 
     * @param guestSessionId 
     */
    tvSeriesAccountStates(seriesId: number, sessionId?: string, guestSessionId?: string, extraHttpRequestParams?: any): Observable<AccountStates>;

    /**
     * Add Rating
     * Rate a TV show and save it to your rated list.
     * @endpoint post /tv/{series_id}/rating
     * @param seriesId 
     * @param contentType 
     * @param guestSessionId 
     * @param sessionId 
     * @param accountAddFavoriteRequest 
     */
    tvSeriesAddRating(seriesId: number, contentType: string, guestSessionId?: string, sessionId?: string, accountAddFavoriteRequest?: AccountAddFavoriteRequest, extraHttpRequestParams?: any): Observable<StatusResponse>;

    /**
     * Aggregate Credits
     * Get the aggregate credits (cast and crew) that have been added to a TV show.
     * @endpoint get /tv/{series_id}/aggregate_credits
     * @param seriesId 
     * @param language 
     */
    tvSeriesAggregateCredits(seriesId: number, language?: string, extraHttpRequestParams?: any): Observable<AggregateCredits>;

    /**
     * Alternative Titles
     * Get the alternative titles that have been added to a TV show.
     * @endpoint get /tv/{series_id}/alternative_titles
     * @param seriesId 
     */
    tvSeriesAlternativeTitles(seriesId: number, extraHttpRequestParams?: any): Observable<TvAlternativeTitleList>;

    /**
     * Changes
     * Get the recent changes for a TV show.
     * @endpoint get /tv/{series_id}/changes
     * @param seriesId 
     * @param endDate 
     * @param page 
     * @param startDate 
     */
    tvSeriesChanges(seriesId: number, endDate?: string, page?: number, startDate?: string, extraHttpRequestParams?: any): Observable<ChangeList>;

    /**
     * Content Ratings
     * Get the content ratings that have been added to a TV show.
     * @endpoint get /tv/{series_id}/content_ratings
     * @param seriesId 
     */
    tvSeriesContentRatings(seriesId: number, extraHttpRequestParams?: any): Observable<ContentRatingList>;

    /**
     * Credits
     * Get the latest season credits of a TV show.
     * @endpoint get /tv/{series_id}/credits
     * @param seriesId 
     * @param language 
     */
    tvSeriesCredits(seriesId: number, language?: string, extraHttpRequestParams?: any): Observable<Credits>;

    /**
     * Delete Rating
     * 
     * @endpoint delete /tv/{series_id}/rating
     * @param seriesId 
     * @param contentType 
     * @param guestSessionId 
     * @param sessionId 
     */
    tvSeriesDeleteRating(seriesId: number, contentType?: string, guestSessionId?: string, sessionId?: string, extraHttpRequestParams?: any): Observable<StatusResponse>;

    /**
     * Details
     * Get the details of a TV show.
     * @endpoint get /tv/{series_id}
     * @param seriesId 
     * @param appendToResponse comma separated list of endpoints within this namespace, 20 items max
     * @param language 
     */
    tvSeriesDetails(seriesId: number, appendToResponse?: string, language?: string, extraHttpRequestParams?: any): Observable<TvSeries>;

    /**
     * Episode Groups
     * Get the episode groups that have been added to a TV show.
     * @endpoint get /tv/{series_id}/episode_groups
     * @param seriesId 
     */
    tvSeriesEpisodeGroups(seriesId: number, extraHttpRequestParams?: any): Observable<EpisodeGroupList>;

    /**
     * External IDs
     * Get a list of external IDs that have been added to a TV show.
     * @endpoint get /tv/{series_id}/external_ids
     * @param seriesId 
     */
    tvSeriesExternalIds(seriesId: number, extraHttpRequestParams?: any): Observable<TvExternalIds>;

    /**
     * Images
     * Get the images that belong to a TV series.
     * @endpoint get /tv/{series_id}/images
     * @param seriesId 
     * @param includeImageLanguage specify a comma separated list of ISO-639-1 values to query, for example: &#x60;en-US,null&#x60;
     * @param language 
     */
    tvSeriesImages(seriesId: number, includeImageLanguage?: string, language?: string, extraHttpRequestParams?: any): Observable<ImageList>;

    /**
     * Keywords
     * Get a list of keywords that have been added to a TV show.
     * @endpoint get /tv/{series_id}/keywords
     * @param seriesId 
     */
    tvSeriesKeywords(seriesId: number, extraHttpRequestParams?: any): Observable<TvKeywordList>;

    /**
     * Recommendations
     * 
     * @endpoint get /tv/{series_id}/recommendations
     * @param seriesId 
     * @param language 
     * @param page 
     */
    tvSeriesRecommendations(seriesId: number, language?: string, page?: number, extraHttpRequestParams?: any): Observable<TvSeriesPage>;

    /**
     * Reviews
     * Get the reviews that have been added to a TV show.
     * @endpoint get /tv/{series_id}/reviews
     * @param seriesId 
     * @param language 
     * @param page 
     */
    tvSeriesReviews(seriesId: number, language?: string, page?: number, extraHttpRequestParams?: any): Observable<ReviewPage>;

    /**
     * Screened Theatrically
     * Get the seasons and episodes that have screened theatrically.
     * @endpoint get /tv/{series_id}/screened_theatrically
     * @param seriesId 
     */
    tvSeriesScreenedTheatrically(seriesId: number, extraHttpRequestParams?: any): Observable<ScreenedTheatricallyList>;

    /**
     * Similar
     * Get the similar TV shows.
     * @endpoint get /tv/{series_id}/similar
     * @param seriesId 
     * @param language 
     * @param page 
     */
    tvSeriesSimilar(seriesId: string, language?: string, page?: number, extraHttpRequestParams?: any): Observable<TvSeriesPage>;

    /**
     * Translations
     * Get the translations that have been added to a TV show.
     * @endpoint get /tv/{series_id}/translations
     * @param seriesId 
     */
    tvSeriesTranslations(seriesId: number, extraHttpRequestParams?: any): Observable<TranslationList>;

    /**
     * Videos
     * Get the videos that belong to a TV show.
     * @endpoint get /tv/{series_id}/videos
     * @param seriesId 
     * @param includeVideoLanguage filter the list results by language, supports more than one value by using a comma
     * @param language 
     */
    tvSeriesVideos(seriesId: number, includeVideoLanguage?: string, language?: string, extraHttpRequestParams?: any): Observable<VideoList>;

    /**
     * Watch Providers
     * Get the list of streaming providers we have for a TV show.
     * @endpoint get /tv/{series_id}/watch/providers
     * @param seriesId 
     */
    tvSeriesWatchProviders(seriesId: number, extraHttpRequestParams?: any): Observable<WatchProviderList>;

}
