/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { WatchProviderCatalog } from '../model/models';
import { WatchProviderRegionList } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface WatchProviderRestControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * TV Providers
     * Get the list of streaming providers we have for TV shows.
     * @endpoint get /watch/providers/tv
     * @param language 
     * @param watchRegion 
     */
    watchProviderTvList(language?: string, watchRegion?: string, extraHttpRequestParams?: any): Observable<WatchProviderCatalog>;

    /**
     * Available Regions
     * Get the list of the countries we have watch provider (OTT/streaming) data for.
     * @endpoint get /watch/providers/regions
     * @param language 
     */
    watchProvidersAvailableRegions(language?: string, extraHttpRequestParams?: any): Observable<WatchProviderRegionList>;

    /**
     * Movie Providers
     * Get the list of streaming providers we have for movies.
     * @endpoint get /watch/providers/movie
     * @param language 
     * @param watchRegion 
     */
    watchProvidersMovieList(language?: string, watchRegion?: string, extraHttpRequestParams?: any): Observable<WatchProviderCatalog>;

}
