/**
 * TMDB API v4 Lists
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { V4AccountListPage } from '../model/models';
import { V4AccountMoviePage } from '../model/models';
import { V4AccountSortBy } from '../model/models';
import { V4AccountTvPage } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AccountServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Favorite Movies
     * Get a user\&#39;s list of favorite movies.
     * @endpoint get /account/{account_object_id}/movie/favorites
     * @param accountObjectId 
     * @param page 
     * @param language 
     * @param sortBy 
     */
    accountV4FavoriteMovies(accountObjectId: string, page?: number, language?: string, sortBy?: V4AccountSortBy, extraHttpRequestParams?: any): Observable<V4AccountMoviePage>;

    /**
     * Favorite TV Shows
     * Get a user\&#39;s list of favorite TV shows.
     * @endpoint get /account/{account_object_id}/tv/favorites
     * @param accountObjectId 
     * @param page 
     * @param language 
     * @param sortBy 
     */
    accountV4FavoriteTv(accountObjectId: string, page?: number, language?: string, sortBy?: V4AccountSortBy, extraHttpRequestParams?: any): Observable<V4AccountTvPage>;

    /**
     * Lists
     * Get the custom lists that a user has created.
     * @endpoint get /account/{account_object_id}/lists
     * @param accountObjectId 
     * @param page 
     */
    accountV4Lists(accountObjectId: string, page?: number, extraHttpRequestParams?: any): Observable<V4AccountListPage>;

    /**
     * Recommended Movies
     * Get a user\&#39;s list of recommended movies.
     * @endpoint get /account/{account_object_id}/movie/recommendations
     * @param accountObjectId 
     * @param page 
     * @param language 
     */
    accountV4MovieRecommendations(accountObjectId: string, page?: number, language?: string, extraHttpRequestParams?: any): Observable<V4AccountMoviePage>;

    /**
     * Watchlist Movies
     * Get a user\&#39;s movie watchlist.
     * @endpoint get /account/{account_object_id}/movie/watchlist
     * @param accountObjectId 
     * @param page 
     * @param language 
     * @param sortBy 
     */
    accountV4MovieWatchlist(accountObjectId: string, page?: number, language?: string, sortBy?: V4AccountSortBy, extraHttpRequestParams?: any): Observable<V4AccountMoviePage>;

    /**
     * Rated Movies
     * Get a user\&#39;s rated movies.
     * @endpoint get /account/{account_object_id}/movie/rated
     * @param accountObjectId 
     * @param page 
     * @param language 
     * @param sortBy 
     */
    accountV4RatedMovies(accountObjectId: string, page?: number, language?: string, sortBy?: V4AccountSortBy, extraHttpRequestParams?: any): Observable<V4AccountMoviePage>;

    /**
     * Rated TV Shows
     * Get a user\&#39;s rated TV shows.
     * @endpoint get /account/{account_object_id}/tv/rated
     * @param accountObjectId 
     * @param page 
     * @param language 
     * @param sortBy 
     */
    accountV4RatedTv(accountObjectId: string, page?: number, language?: string, sortBy?: V4AccountSortBy, extraHttpRequestParams?: any): Observable<V4AccountTvPage>;

    /**
     * Recommended TV Shows
     * Get a user\&#39;s list of recommended TV shows.
     * @endpoint get /account/{account_object_id}/tv/recommendations
     * @param accountObjectId 
     * @param page 
     * @param language 
     */
    accountV4TvRecommendations(accountObjectId: string, page?: number, language?: string, extraHttpRequestParams?: any): Observable<V4AccountTvPage>;

    /**
     * Watchlist TV Shows
     * Get a user\&#39;s TV watchlist.
     * @endpoint get /account/{account_object_id}/tv/watchlist
     * @param accountObjectId 
     * @param page 
     * @param language 
     * @param sortBy 
     */
    accountV4TvWatchlist(accountObjectId: string, page?: number, language?: string, sortBy?: V4AccountSortBy, extraHttpRequestParams?: any): Observable<V4AccountTvPage>;

}
