export * from './account.service';
import { AccountService } from './account.service';
export * from './account.serviceInterface';
export * from './authentication.service';
import { AuthenticationService } from './authentication.service';
export * from './authentication.serviceInterface';
export * from './list.service';
import { ListService } from './list.service';
export * from './list.serviceInterface';
export const APIS = [AccountService, AuthenticationService, ListService];
