/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AccountStates { 
    id?: number;
    favorite?: boolean;
    rated?: any | null;
    watchlist?: boolean;
}

