/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountRatedMovies200ResponseResultsInner } from './accountRatedMovies200ResponseResultsInner';


export interface AccountRatedMovies200Response { 
    page?: number;
    results?: Array<AccountRatedMovies200ResponseResultsInner>;
    total_pages?: number;
    total_results?: number;
}

