/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CompanyListItem } from './companyListItem';


export interface CompanyPage { 
    page?: number;
    results?: Array<CompanyListItem>;
    total_pages?: number;
    total_results?: number;
}

