/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrganizationLogo } from './organizationLogo';


export interface CompanyImages200Response { 
    id?: number;
    logos?: Array<OrganizationLogo>;
}

