/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreditDetailsPerson { 
    adult?: boolean;
    gender?: number;
    name?: string;
    id?: number;
    known_for_department?: string;
    original_name?: string;
    popularity?: number;
    profile_path?: string | null;
}

