/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EpisodeGroup } from './episodeGroup';


export interface EpisodeGroupList { 
    results?: Array<EpisodeGroup>;
    id?: number;
}

