/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieListItem } from './movieListItem';
import { TvSeasonCompact } from './tvSeasonCompact';
import { PersonListItem } from './personListItem';
import { TvEpisodeCompact } from './tvEpisodeCompact';
import { TvSeriesListItem } from './tvSeriesListItem';


export interface FindResult { 
    movie_results?: Array<MovieListItem>;
    person_results?: Array<PersonListItem>;
    tv_results?: Array<TvSeriesListItem>;
    tv_episode_results?: Array<TvEpisodeCompact>;
    tv_season_results?: Array<TvSeasonCompact>;
}

