/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Image } from './image';


export interface ImageList { 
    backdrops?: Array<Image>;
    id?: number;
    logos?: Array<Image>;
    posters?: Array<Image>;
}

