/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { KeywordListItem } from './keywordListItem';


export interface KeywordPage { 
    page?: number;
    results?: Array<KeywordListItem>;
    total_pages?: number;
    total_results?: number;
}

