/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Language { 
    /**
     * ISO 639-1 tag
     */
    iso_639_1: string;
    english_name: string;
    name?: string;
}

