/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieListItem } from './movieListItem';


export interface ListDetails { 
    created_by?: string;
    description?: string;
    favorite_count?: number;
    id?: number;
    items?: Array<MovieListItem>;
    item_count?: number;
    iso_639_1?: string;
    name?: string;
    poster_path?: string | null;
}

