/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MediaChangeItem } from './mediaChangeItem';


export interface MediaChangePage { 
    results?: Array<MediaChangeItem>;
    page?: number;
    total_pages?: number;
    total_results?: number;
}

