/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Media { 
    media_type: Media.MediaTypeEnum;
}
export namespace Media {
    export const MediaTypeEnum = {
        MediaTypeMovie: 'movie',
        MediaTypePerson: 'person',
        MediaTypeTv: 'tv'
    } as const;
    export type MediaTypeEnum = typeof MediaTypeEnum[keyof typeof MediaTypeEnum];
}


