/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieWatchProviders200ResponseResultsHKFlatrateInner } from './movieWatchProviders200ResponseResultsHKFlatrateInner';


export interface MovieWatchProviders200ResponseResultsHK { 
    link?: string;
    flatrate?: Array<MovieWatchProviders200ResponseResultsHKFlatrateInner>;
}

