/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModelObject } from './modelObject';


export interface MovieKeywords200Response { 
    id: number;
    keywords: Array<ModelObject>;
}

