/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieWatchProviders200ResponseResultsMYFlatrateInner } from './movieWatchProviders200ResponseResultsMYFlatrateInner';


export interface MovieWatchProviders200ResponseResultsTH { 
    link?: string;
    flatrate?: Array<MovieWatchProviders200ResponseResultsMYFlatrateInner>;
}

