/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieChanges200ResponseChangesInnerItemsInner } from './movieChanges200ResponseChangesInnerItemsInner';


export interface MovieChanges200ResponseChangesInner { 
    key?: string;
    items?: Array<MovieChanges200ResponseChangesInnerItemsInner>;
}

