/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MultiListItem } from './multiListItem';


export interface MultiPage { 
    page?: number;
    results?: Array<MultiListItem>;
    total_pages?: number;
    total_results?: number;
}

