/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MultiListPageAllOfResults } from './multiListPageAllOfResults';


export interface MultiListPage { 
    page: number;
    total_pages: number;
    total_results: number;
    results: Array<MultiListPageAllOfResults>;
}

