/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PersonTranslation } from './personTranslation';


export interface PersonTranslationList { 
    id?: number;
    translations?: Array<PersonTranslation>;
}

