/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PersonCombinedCrewCredit { 
    adult?: boolean;
    backdrop_path?: string | null;
    genre_ids?: Array<number>;
    id?: number;
    original_language?: string;
    overview?: string;
    popularity?: number;
    poster_path?: string | null;
    vote_average?: number;
    vote_count?: number;
    media_type?: PersonCombinedCrewCreditMediaTypeEnum;
    original_title?: string;
    release_date?: string;
    title?: string;
    video?: boolean;
    original_name?: string;
    first_air_date?: string;
    name?: string;
    origin_country?: Array<string>;
    episode_count?: number;
    credit_id?: string;
    department?: string;
    job?: string;
}
export enum PersonCombinedCrewCreditMediaTypeEnum {
    movie = 'movie',
    tv = 'tv'
};



