/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PersonExternalIds { 
    id?: number;
    freebase_mid?: string | null;
    freebase_id?: string | null;
    imdb_id?: string | null;
    tvrage_id?: number | null;
    wikidata_id?: string | null;
    facebook_id?: string | null;
    instagram_id?: string | null;
    tiktok_id?: string | null;
    twitter_id?: string | null;
    youtube_id?: string | null;
}

