/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PersonTvCrewCredit } from './personTvCrewCredit';
import { PersonTvCastCredit } from './personTvCastCredit';


export interface PersonTvCredits { 
    cast?: Array<PersonTvCastCredit>;
    crew?: Array<PersonTvCrewCredit>;
    id?: number;
}

