/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PersonListItemKnownForInner } from './personListItemKnownForInner';


export interface PersonListItem { 
    id: number;
    name: string;
    original_name: string;
    adult?: boolean;
    gender?: number;
    known_for_department?: string;
    popularity?: number;
    profile_path?: string;
    known_for?: Array<PersonListItemKnownForInner>;
}

