/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvListItemWithMediaType } from './tvListItemWithMediaType';
import { MovieListItemWithMediaType } from './movieListItemWithMediaType';


/**
 * @type PersonListItemKnownForInner
 * @export
 */
export type PersonListItemKnownForInner = MovieListItemWithMediaType | TvListItemWithMediaType;

