/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RatedTvEpisodeListItem } from './ratedTvEpisodeListItem';


export interface RatedTvEpisodePage { 
    page?: number;
    results?: Array<RatedTvEpisodeListItem>;
    total_pages?: number;
    total_results?: number;
}

