/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RatedMovieListItem } from './ratedMovieListItem';


export interface RatedMoviePage { 
    page?: number;
    results?: Array<RatedMovieListItem>;
    total_pages?: number;
    total_results?: number;
}

