/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuthorDetails } from './authorDetails';


export interface ReviewDetails { 
    id?: string;
    author?: string;
    author_details?: AuthorDetails;
    content?: string;
    created_at?: string;
    iso_639_1?: string;
    media_id?: number;
    media_title?: string;
    media_type?: string;
    updated_at?: string;
    url?: string;
}

