/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TaggedImage { 
    aspect_ratio?: number;
    file_path?: string;
    height?: number;
    id?: string;
    iso_639_1?: string | null;
    vote_average?: number;
    vote_count?: number;
    width?: number;
    image_type?: string;
    media_type?: string;
    media?: object;
}

