/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Translation } from './translation';


export interface TranslationList { 
    id?: number;
    translations?: Array<Translation>;
}

