/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TvEpisodeCompact { 
    id?: number;
    name?: string;
    overview?: string;
    vote_average?: number;
    vote_count?: number;
    air_date?: string;
    episode_number?: number;
    episode_type?: string;
    production_code?: string;
    runtime?: number | null;
    season_number?: number;
    show_id?: number;
    still_path?: string | null;
}

