/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TvEpisodeBase { 
    /**
     * The identifier property represents any kind of identifier for any kind of [Thing](https://schema.org/Thing), such as ISBNs, GTIN codes, UUIDs etc. 
     */
    id: number;
    name: string;
    air_date?: string;
    episode_number?: number;
    overview?: string;
    production_code?: string;
    runtime?: number;
    season_number?: number;
    still_path?: string;
    vote_average?: number;
    vote_count?: number;
}

