/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TvListItem { 
    /**
     * The identifier property represents any kind of identifier for any kind of [Thing](https://schema.org/Thing), such as ISBNs, GTIN codes, UUIDs etc. 
     */
    id: number;
    name: string;
    adult?: boolean;
    backdrop_path?: string;
    first_air_date?: string;
    origin_country?: Array<string>;
    original_language: string;
    original_name: string;
    overview?: string;
    popularity?: number;
    poster_path?: string;
    vote_average?: number;
    vote_count?: number;
    genre_ids?: Array<number>;
}

