/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeasonWatchProviders200ResponseResultsCAFlatrateInner } from './tvSeasonWatchProviders200ResponseResultsCAFlatrateInner';
import { TvSeasonWatchProviders200ResponseResultsCABuyInner } from './tvSeasonWatchProviders200ResponseResultsCABuyInner';


export interface TvSeasonWatchProviders200ResponseResultsCA { 
    link?: string;
    flatrate?: Array<TvSeasonWatchProviders200ResponseResultsCAFlatrateInner>;
    buy?: Array<TvSeasonWatchProviders200ResponseResultsCABuyInner>;
}

