/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeasonWatchProviders200ResponseResultsDEBuyInner } from './tvSeasonWatchProviders200ResponseResultsDEBuyInner';
import { TvSeasonWatchProviders200ResponseResultsGBFlatrateInner } from './tvSeasonWatchProviders200ResponseResultsGBFlatrateInner';


export interface TvSeasonWatchProviders200ResponseResultsGB { 
    link?: string;
    buy?: Array<TvSeasonWatchProviders200ResponseResultsDEBuyInner>;
    flatrate?: Array<TvSeasonWatchProviders200ResponseResultsGBFlatrateInner>;
}

