/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeriesWatchProviders200ResponseResultsCZFlatrateInner } from './tvSeriesWatchProviders200ResponseResultsCZFlatrateInner';


export interface TvSeriesWatchProviders200ResponseResultsHU { 
    link?: string;
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsCZFlatrateInner>;
}

