/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeriesWatchProviders200ResponseResultsSCFlatrateInner } from './tvSeriesWatchProviders200ResponseResultsSCFlatrateInner';


export interface TvSeriesWatchProviders200ResponseResultsSC { 
    link?: string;
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsSCFlatrateInner>;
}

