/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeasonWatchProviders200ResponseResultsATFlatrateInner } from './tvSeasonWatchProviders200ResponseResultsATFlatrateInner';
import { TvSeasonWatchProviders200ResponseResultsATBuyInner } from './tvSeasonWatchProviders200ResponseResultsATBuyInner';


export interface TvSeasonWatchProviders200ResponseResultsAT { 
    link?: string;
    buy?: Array<TvSeasonWatchProviders200ResponseResultsATBuyInner>;
    flatrate?: Array<TvSeasonWatchProviders200ResponseResultsATFlatrateInner>;
}

