/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeasonWatchProviders200ResponseResultsCIFlatrateInner } from './tvSeasonWatchProviders200ResponseResultsCIFlatrateInner';


export interface TvSeasonWatchProviders200ResponseResultsCI { 
    link?: string;
    flatrate?: Array<TvSeasonWatchProviders200ResponseResultsCIFlatrateInner>;
}

