/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeasonWatchProviders200ResponseResultsJMFlatrateInner } from './tvSeasonWatchProviders200ResponseResultsJMFlatrateInner';


export interface TvSeasonWatchProviders200ResponseResultsJM { 
    link?: string;
    flatrate?: Array<TvSeasonWatchProviders200ResponseResultsJMFlatrateInner>;
}

