/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeasonWatchProviders200ResponseResultsZAFlatrateInner } from './tvSeasonWatchProviders200ResponseResultsZAFlatrateInner';


export interface TvSeasonWatchProviders200ResponseResultsZA { 
    link?: string;
    flatrate?: Array<TvSeasonWatchProviders200ResponseResultsZAFlatrateInner>;
}

