/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeasonWatchProviders200ResponseResultsINFlatrateInner } from './tvSeasonWatchProviders200ResponseResultsINFlatrateInner';


export interface TvSeasonWatchProviders200ResponseResultsIN { 
    link?: string;
    flatrate?: Array<TvSeasonWatchProviders200ResponseResultsINFlatrateInner>;
}

