/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeriesWatchProviders200ResponseResultsCIFlatrateInner } from './tvSeriesWatchProviders200ResponseResultsCIFlatrateInner';


export interface TvSeriesWatchProviders200ResponseResultsNE { 
    link?: string;
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsCIFlatrateInner>;
}

