/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeasonWatchProviders200ResponseResultsDEBuyInner } from './tvSeasonWatchProviders200ResponseResultsDEBuyInner';
import { TvSeasonWatchProviders200ResponseResultsATFlatrateInner } from './tvSeasonWatchProviders200ResponseResultsATFlatrateInner';


export interface TvSeasonWatchProviders200ResponseResultsDE { 
    link?: string;
    flatrate?: Array<TvSeasonWatchProviders200ResponseResultsATFlatrateInner>;
    buy?: Array<TvSeasonWatchProviders200ResponseResultsDEBuyInner>;
}

