/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeriesTopRatedList200ResponseResultsInner } from './tvSeriesTopRatedList200ResponseResultsInner';


export interface TvSeriesTopRatedList200Response { 
    page?: number;
    results?: Array<TvSeriesTopRatedList200ResponseResultsInner>;
    total_pages?: number;
    total_results?: number;
}

