/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeasonWatchProviders200ResponseResultsECFlatrateInner } from './tvSeasonWatchProviders200ResponseResultsECFlatrateInner';


export interface TvSeasonWatchProviders200ResponseResultsEC { 
    link?: string;
    flatrate?: Array<TvSeasonWatchProviders200ResponseResultsECFlatrateInner>;
}

