/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeasonWatchProviders200ResponseResultsLCFlatrateInner } from './tvSeasonWatchProviders200ResponseResultsLCFlatrateInner';


export interface TvSeasonWatchProviders200ResponseResultsTC { 
    link?: string;
    flatrate?: Array<TvSeasonWatchProviders200ResponseResultsLCFlatrateInner>;
}

