/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieWatchProviders200ResponseResultsKRBuyInner } from './movieWatchProviders200ResponseResultsKRBuyInner';


export interface TvSeriesWatchProviders200ResponseResultsKR { 
    link?: string;
    flatrate?: Array<MovieWatchProviders200ResponseResultsKRBuyInner>;
}

