/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieWatchProviders200ResponseResultsMKFlatrateInner } from './movieWatchProviders200ResponseResultsMKFlatrateInner';


export interface TvSeriesWatchProviders200ResponseResultsSI { 
    link?: string;
    flatrate?: Array<MovieWatchProviders200ResponseResultsMKFlatrateInner>;
}

