/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeasonWatchProviders200ResponseResultsCLFlatrateInner } from './tvSeasonWatchProviders200ResponseResultsCLFlatrateInner';


export interface TvSeasonWatchProviders200ResponseResultsPE { 
    link?: string;
    flatrate?: Array<TvSeasonWatchProviders200ResponseResultsCLFlatrateInner>;
}

