/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeriesWatchProviders200ResponseResultsMUFlatrateInner } from './tvSeriesWatchProviders200ResponseResultsMUFlatrateInner';


export interface TvSeriesWatchProviders200ResponseResultsMU { 
    link?: string;
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsMUFlatrateInner>;
}

