/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeasonWatchProviders200ResponseResultsDKFlatrateInner } from './tvSeasonWatchProviders200ResponseResultsDKFlatrateInner';


export interface TvSeasonWatchProviders200ResponseResultsID { 
    link?: string;
    flatrate?: Array<TvSeasonWatchProviders200ResponseResultsDKFlatrateInner>;
}

