/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TvSeriesContentRatings200ResponseResultsInner { 
    descriptors?: Array<any>;
    iso_3166_1?: string;
    rating?: string;
}

