/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeasonWatchProviders200ResponseResultsCMFlatrateInner } from './tvSeasonWatchProviders200ResponseResultsCMFlatrateInner';


export interface TvSeasonWatchProviders200ResponseResultsCM { 
    link?: string;
    flatrate?: Array<TvSeasonWatchProviders200ResponseResultsCMFlatrateInner>;
}

