/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeasonWatchProviders200ResponseResultsHKFlatrateInner } from './tvSeasonWatchProviders200ResponseResultsHKFlatrateInner';


export interface TvSeasonWatchProviders200ResponseResultsTW { 
    link?: string;
    flatrate?: Array<TvSeasonWatchProviders200ResponseResultsHKFlatrateInner>;
}

