/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeasonTranslations200ResponseTranslationsInnerData } from './tvSeasonTranslations200ResponseTranslationsInnerData';


export interface TvSeasonTranslations200ResponseTranslationsInner { 
    iso_3166_1?: string;
    iso_639_1?: string;
    name?: string;
    english_name?: string;
    data?: TvSeasonTranslations200ResponseTranslationsInnerData;
}

