/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieWatchProviders200ResponseResultsJMFlatrateInner } from './movieWatchProviders200ResponseResultsJMFlatrateInner';


export interface TvSeriesWatchProviders200ResponseResultsPA { 
    link?: string;
    flatrate?: Array<MovieWatchProviders200ResponseResultsJMFlatrateInner>;
}

