/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeasonWatchProviders200ResponseResultsSKFlatrateInner } from './tvSeasonWatchProviders200ResponseResultsSKFlatrateInner';


export interface TvSeasonWatchProviders200ResponseResultsSK { 
    link?: string;
    flatrate?: Array<TvSeasonWatchProviders200ResponseResultsSKFlatrateInner>;
}

