/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeasonWatchProviders200ResponseResultsBEBuyInner } from './tvSeasonWatchProviders200ResponseResultsBEBuyInner';
import { TvSeasonWatchProviders200ResponseResultsBEFlatrateInner } from './tvSeasonWatchProviders200ResponseResultsBEFlatrateInner';


export interface TvSeasonWatchProviders200ResponseResultsBE { 
    link?: string;
    buy?: Array<TvSeasonWatchProviders200ResponseResultsBEBuyInner>;
    flatrate?: Array<TvSeasonWatchProviders200ResponseResultsBEFlatrateInner>;
}

