/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeasonWatchProviders200ResponseResultsIEFlatrateInner } from './tvSeasonWatchProviders200ResponseResultsIEFlatrateInner';
import { TvSeasonWatchProviders200ResponseResultsIEBuyInner } from './tvSeasonWatchProviders200ResponseResultsIEBuyInner';


export interface TvSeasonWatchProviders200ResponseResultsIE { 
    link?: string;
    flatrate?: Array<TvSeasonWatchProviders200ResponseResultsIEFlatrateInner>;
    buy?: Array<TvSeasonWatchProviders200ResponseResultsIEBuyInner>;
}

