/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeasonWatchProviders200ResponseResultsRUFlatrateInner } from './tvSeasonWatchProviders200ResponseResultsRUFlatrateInner';


export interface TvSeasonWatchProviders200ResponseResultsRU { 
    link?: string;
    flatrate?: Array<TvSeasonWatchProviders200ResponseResultsRUFlatrateInner>;
}

