/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeasonWatchProviders200ResponseResultsBZFlatrateInner } from './tvSeasonWatchProviders200ResponseResultsBZFlatrateInner';


export interface TvSeasonWatchProviders200ResponseResultsBZ { 
    link?: string;
    flatrate?: Array<TvSeasonWatchProviders200ResponseResultsBZFlatrateInner>;
}

