/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeasonWatchProviders200ResponseResultsJPBuyInner } from './tvSeasonWatchProviders200ResponseResultsJPBuyInner';
import { TvSeasonWatchProviders200ResponseResultsJPFlatrateInner } from './tvSeasonWatchProviders200ResponseResultsJPFlatrateInner';


export interface TvSeasonWatchProviders200ResponseResultsJP { 
    link?: string;
    flatrate?: Array<TvSeasonWatchProviders200ResponseResultsJPFlatrateInner>;
    buy?: Array<TvSeasonWatchProviders200ResponseResultsJPBuyInner>;
    rent?: Array<TvSeasonWatchProviders200ResponseResultsJPBuyInner>;
}

