/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeasonWatchProviders200ResponseResultsBOFlatrateInner } from './tvSeasonWatchProviders200ResponseResultsBOFlatrateInner';


export interface TvSeasonWatchProviders200ResponseResultsSV { 
    link?: string;
    flatrate?: Array<TvSeasonWatchProviders200ResponseResultsBOFlatrateInner>;
}

