/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeasonWatchProviders200ResponseResultsUSBuyInner } from './tvSeasonWatchProviders200ResponseResultsUSBuyInner';
import { TvSeasonWatchProviders200ResponseResultsAGFlatrateInner } from './tvSeasonWatchProviders200ResponseResultsAGFlatrateInner';


export interface TvSeasonWatchProviders200ResponseResultsUS { 
    link?: string;
    flatrate?: Array<TvSeasonWatchProviders200ResponseResultsAGFlatrateInner>;
    buy?: Array<TvSeasonWatchProviders200ResponseResultsUSBuyInner>;
}

