/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeasonWatchProviders200ResponseResultsBHFlatrateInner } from './tvSeasonWatchProviders200ResponseResultsBHFlatrateInner';


export interface TvSeasonWatchProviders200ResponseResultsBH { 
    link?: string;
    flatrate?: Array<TvSeasonWatchProviders200ResponseResultsBHFlatrateInner>;
}

