/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TvSeriesDetails200ResponseCreatedByInner { 
    id?: number;
    credit_id?: string;
    name?: string;
    gender?: number;
    profile_path?: string;
}

