/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeriesWatchProviders200ResponseResultsPHFlatrateInner } from './tvSeriesWatchProviders200ResponseResultsPHFlatrateInner';


export interface TvSeriesWatchProviders200ResponseResultsPH { 
    link?: string;
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsPHFlatrateInner>;
}

