/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeriesVideos200ResponseResultsInner } from './tvSeriesVideos200ResponseResultsInner';


export interface TvSeriesVideos200Response { 
    id?: number;
    results?: Array<TvSeriesVideos200ResponseResultsInner>;
}

