/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeriesWatchProviders200ResponseResultsGHFlatrateInner } from './tvSeriesWatchProviders200ResponseResultsGHFlatrateInner';


export interface TvSeriesWatchProviders200ResponseResultsSN { 
    link?: string;
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsGHFlatrateInner>;
}

