/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeasonWatchProviders200ResponseResultsGYFlatrateInner } from './tvSeasonWatchProviders200ResponseResultsGYFlatrateInner';


export interface TvSeasonWatchProviders200ResponseResultsGY { 
    link?: string;
    flatrate?: Array<TvSeasonWatchProviders200ResponseResultsGYFlatrateInner>;
}

