/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeasonWatchProviders200ResponseResultsNLBuyInner } from './tvSeasonWatchProviders200ResponseResultsNLBuyInner';
import { TvSeasonWatchProviders200ResponseResultsNLFlatrateInner } from './tvSeasonWatchProviders200ResponseResultsNLFlatrateInner';


export interface TvSeasonWatchProviders200ResponseResultsNL { 
    link?: string;
    buy?: Array<TvSeasonWatchProviders200ResponseResultsNLBuyInner>;
    flatrate?: Array<TvSeasonWatchProviders200ResponseResultsNLFlatrateInner>;
}

