/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeasonWatchProviders200ResponseResultsMKFlatrateInner } from './tvSeasonWatchProviders200ResponseResultsMKFlatrateInner';


export interface TvSeasonWatchProviders200ResponseResultsMK { 
    link?: string;
    flatrate?: Array<TvSeasonWatchProviders200ResponseResultsMKFlatrateInner>;
}

