/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeasonWatchProviders200ResponseResultsGQFlatrateInner } from './tvSeasonWatchProviders200ResponseResultsGQFlatrateInner';


export interface TvSeasonWatchProviders200ResponseResultsMZ { 
    link?: string;
    flatrate?: Array<TvSeasonWatchProviders200ResponseResultsGQFlatrateInner>;
}

