/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeasonWatchProviders200ResponseResultsPLFlatrateInner } from './tvSeasonWatchProviders200ResponseResultsPLFlatrateInner';
import { TvSeasonWatchProviders200ResponseResultsPLBuyInner } from './tvSeasonWatchProviders200ResponseResultsPLBuyInner';


export interface TvSeasonWatchProviders200ResponseResultsPL { 
    link?: string;
    flatrate?: Array<TvSeasonWatchProviders200ResponseResultsPLFlatrateInner>;
    buy?: Array<TvSeasonWatchProviders200ResponseResultsPLBuyInner>;
}

