/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeriesWatchProviders200ResponseResultsFIBuyInner } from './tvSeriesWatchProviders200ResponseResultsFIBuyInner';
import { TvSeriesWatchProviders200ResponseResultsNLFlatrateInner } from './tvSeriesWatchProviders200ResponseResultsNLFlatrateInner';


export interface TvSeriesWatchProviders200ResponseResultsNL { 
    link?: string;
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsNLFlatrateInner>;
    buy?: Array<TvSeriesWatchProviders200ResponseResultsFIBuyInner>;
}

