/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeasonWatchProviders200ResponseResultsBAFlatrateInner } from './tvSeasonWatchProviders200ResponseResultsBAFlatrateInner';


export interface TvSeasonWatchProviders200ResponseResultsVE { 
    link?: string;
    flatrate?: Array<TvSeasonWatchProviders200ResponseResultsBAFlatrateInner>;
}

