/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieWatchProviders200ResponseResultsMDFlatrateInner } from './movieWatchProviders200ResponseResultsMDFlatrateInner';


export interface TvSeriesWatchProviders200ResponseResultsMD { 
    link?: string;
    flatrate?: Array<MovieWatchProviders200ResponseResultsMDFlatrateInner>;
}

