/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvEpisode } from './tvEpisode';


export interface TvSeason { 
    _id?: string;
    air_date?: string;
    episodes?: Array<TvEpisode>;
    name?: string;
    overview?: string;
    id?: number;
    poster_path?: string | null;
    season_number?: number;
    vote_average?: number;
}

