/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeriesWatchProviders200ResponseResultsRSFlatrateInner } from './tvSeriesWatchProviders200ResponseResultsRSFlatrateInner';


export interface TvSeriesWatchProviders200ResponseResultsRS { 
    link?: string;
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsRSFlatrateInner>;
}

