/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeasonWatchProviders200ResponseResultsBRFlatrateInner } from './tvSeasonWatchProviders200ResponseResultsBRFlatrateInner';


export interface TvSeasonWatchProviders200ResponseResultsME { 
    link?: string;
    flatrate?: Array<TvSeasonWatchProviders200ResponseResultsBRFlatrateInner>;
}

