/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeriesWatchProviders200ResponseResultsBRFlatrateInner } from './tvSeriesWatchProviders200ResponseResultsBRFlatrateInner';


export interface TvSeriesWatchProviders200ResponseResultsCL { 
    link?: string;
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsBRFlatrateInner>;
}

