/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TvSeasonAggregateCredits200ResponseCastInnerRolesInner { 
    credit_id?: string;
    character?: string;
    episode_count?: number;
}

