/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeasonChangesById200ResponseChangesInnerItemsInner } from './tvSeasonChangesById200ResponseChangesInnerItemsInner';


export interface TvSeasonChangesById200ResponseChangesInner { 
    key?: string;
    items?: Array<TvSeasonChangesById200ResponseChangesInnerItemsInner>;
}

