/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeasonWatchProviders200ResponseResultsCHBuyInner } from './tvSeasonWatchProviders200ResponseResultsCHBuyInner';
import { TvSeasonWatchProviders200ResponseResultsCHFlatrateInner } from './tvSeasonWatchProviders200ResponseResultsCHFlatrateInner';


export interface TvSeasonWatchProviders200ResponseResultsCH { 
    link?: string;
    buy?: Array<TvSeasonWatchProviders200ResponseResultsCHBuyInner>;
    flatrate?: Array<TvSeasonWatchProviders200ResponseResultsCHFlatrateInner>;
}

