/**
 * tmdb-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TvSeriesWatchProviders200ResponseResultsAEFlatrateInner } from './tvSeriesWatchProviders200ResponseResultsAEFlatrateInner';


export interface TvSeriesWatchProviders200ResponseResultsAE { 
    link?: string;
    flatrate?: Array<TvSeriesWatchProviders200ResponseResultsAEFlatrateInner>;
}

