/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WatchProviderItem } from './watchProviderItem';


export interface WatchProviderCountry { 
    link?: string;
    flatrate?: Array<WatchProviderItem>;
    rent?: Array<WatchProviderItem>;
    buy?: Array<WatchProviderItem>;
}

