/**
 * TMDB API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WatchProviderRegion } from './watchProviderRegion';


export interface WatchProviderRegionList { 
    results?: Array<WatchProviderRegion>;
}

