/**
 * TMDB API v4 Lists
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface V4AccountListSummary { 
    account_object_id?: string;
    id?: number;
    name?: string;
    description?: string;
    number_of_items?: number;
    poster_path?: string | null;
}

