/**
 * TMDB API v4 Lists
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { V4ListContentItem } from './v4ListContentItem';
import { V4ListSortBy } from './v4ListSortBy';


export interface V4ListDetails { 
    id?: number;
    name?: string;
    description?: string;
    created_by?: string;
    created_at?: string;
    updated_at?: string;
    sort_by?: V4ListSortBy;
    'public'?: boolean;
    favorite_count?: number;
    item_count?: number;
    poster_path?: string | null;
    page?: number;
    total_pages?: number;
    total_results?: number;
    results?: Array<V4ListContentItem>;
}
export namespace V4ListDetails {
}


