/**
 * TMDB API v4 Lists
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface V4ListDetailsCreatedBy { 
    avatar_path?: string | null;
    gravatar_hash?: string;
    id?: string;
    name?: string;
    username?: string;
}

