/**
 * TMDB API v4 Lists
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { V4ListItemInput } from './v4ListItemInput';


export interface V4ListItemsRequest { 
    items: Array<V4ListItemInput>;
}

