/**
 * TMDB API v4 Lists
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface V4RequestTokenResponse { 
    success?: boolean;
    status_code?: number;
    status_message?: string;
    request_token?: string;
}

