/**
 * TMDB API v4 Lists
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { V4ListSortBy } from './v4ListSortBy';


export interface V4UpdateListRequest { 
    name?: string;
    description?: string;
    'public'?: boolean;
    sort_by?: V4ListSortBy;
}
export namespace V4UpdateListRequest {
}


